# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05Model\"\x1f\n\x11GetDatasetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x16\n\x07Rowdata\x12\x0b\n\x03row\x18\x01 \x03(\t\"U\n\x12GetDatasetResponse\x12\x1c\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0e.Model.Rowdata\x12\x0e\n\x06labels\x18\x02 \x03(\t\x12\x11\n\tlabelType\x18\x03 \x03(\t\"Y\n\x08TreeNode\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\t\x12\x10\n\x06result\x18\x02 \x01(\tH\x00\x12!\n\x08\x62ranches\x18\x03 \x01(\x0b\x32\r.Model.BranchH\x00\x42\x07\n\x05value\"y\n\x06\x42ranch\x12-\n\x08\x62ranches\x18\x01 \x03(\x0b\x32\x1b.Model.Branch.BranchesEntry\x1a@\n\rBranchesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.Model.TreeNode:\x02\x38\x01\"\x83\x01\n\x11\x43ommitTreeRequest\x12\x30\n\x04tree\x18\x01 \x03(\x0b\x32\".Model.CommitTreeRequest.TreeEntry\x1a<\n\tTreeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.Model.TreeNode:\x02\x38\x01\" \n\x12\x43ommitTreeResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x8f\x01\n\x07Manager\x12\x41\n\nGetDataSet\x12\x18.Model.GetDatasetRequest\x1a\x19.Model.GetDatasetResponse\x12\x41\n\nCommitTree\x12\x18.Model.CommitTreeRequest\x1a\x19.Model.CommitTreeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BRANCH_BRANCHESENTRY']._loaded_options = None
  _globals['_BRANCH_BRANCHESENTRY']._serialized_options = b'8\001'
  _globals['_COMMITTREEREQUEST_TREEENTRY']._loaded_options = None
  _globals['_COMMITTREEREQUEST_TREEENTRY']._serialized_options = b'8\001'
  _globals['_GETDATASETREQUEST']._serialized_start=22
  _globals['_GETDATASETREQUEST']._serialized_end=53
  _globals['_ROWDATA']._serialized_start=55
  _globals['_ROWDATA']._serialized_end=77
  _globals['_GETDATASETRESPONSE']._serialized_start=79
  _globals['_GETDATASETRESPONSE']._serialized_end=164
  _globals['_TREENODE']._serialized_start=166
  _globals['_TREENODE']._serialized_end=255
  _globals['_BRANCH']._serialized_start=257
  _globals['_BRANCH']._serialized_end=378
  _globals['_BRANCH_BRANCHESENTRY']._serialized_start=314
  _globals['_BRANCH_BRANCHESENTRY']._serialized_end=378
  _globals['_COMMITTREEREQUEST']._serialized_start=381
  _globals['_COMMITTREEREQUEST']._serialized_end=512
  _globals['_COMMITTREEREQUEST_TREEENTRY']._serialized_start=452
  _globals['_COMMITTREEREQUEST_TREEENTRY']._serialized_end=512
  _globals['_COMMITTREERESPONSE']._serialized_start=514
  _globals['_COMMITTREERESPONSE']._serialized_end=546
  _globals['_MANAGER']._serialized_start=549
  _globals['_MANAGER']._serialized_end=692
# @@protoc_insertion_point(module_scope)
