# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import service_pb2 as service__pb2


class ManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDataSet = channel.unary_unary(
                '/Model.Manager/GetDataSet',
                request_serializer=service__pb2.GetDataSetRequest.SerializeToString,
                response_deserializer=service__pb2.GetDataSetResponse.FromString,
                )
        self.CommitTree = channel.unary_unary(
                '/Model.Manager/CommitTree',
                request_serializer=service__pb2.CommitTreeRequest.SerializeToString,
                response_deserializer=service__pb2.CommitTreeResponse.FromString,
                )


class ManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDataSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDataSet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataSet,
                    request_deserializer=service__pb2.GetDataSetRequest.FromString,
                    response_serializer=service__pb2.GetDataSetResponse.SerializeToString,
            ),
            'CommitTree': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTree,
                    request_deserializer=service__pb2.CommitTreeRequest.FromString,
                    response_serializer=service__pb2.CommitTreeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Model.Manager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Manager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDataSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Model.Manager/GetDataSet',
            service__pb2.GetDataSetRequest.SerializeToString,
            service__pb2.GetDataSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Model.Manager/CommitTree',
            service__pb2.CommitTreeRequest.SerializeToString,
            service__pb2.CommitTreeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
