# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='Model',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\x12\x05Model\"\x1f\n\x11GetDataSetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x80\x01\n\x12GetDataSetResponse\x12/\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32!.Model.GetDataSetResponse.Rowdata\x12\x0e\n\x06labels\x18\x02 \x03(\t\x12\x11\n\tlabelType\x18\x03 \x03(\t\x1a\x16\n\x07Rowdata\x12\x0b\n\x03row\x18\x01 \x03(\t\"Y\n\x08TreeNode\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\t\x12\x10\n\x06result\x18\x02 \x01(\tH\x00\x12!\n\x08\x62ranches\x18\x03 \x01(\x0b\x32\r.Model.BranchH\x00\x42\x07\n\x05value\"y\n\x06\x42ranch\x12-\n\x08\x62ranches\x18\x01 \x03(\x0b\x32\x1b.Model.Branch.BranchesEntry\x1a@\n\rBranchesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.Model.TreeNode:\x02\x38\x01\"\x83\x01\n\x11\x43ommitTreeRequest\x12\x30\n\x04tree\x18\x01 \x03(\x0b\x32\".Model.CommitTreeRequest.TreeEntry\x1a<\n\tTreeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.Model.TreeNode:\x02\x38\x01\" \n\x12\x43ommitTreeResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x8f\x01\n\x07Manager\x12\x41\n\nGetDataSet\x12\x18.Model.GetDataSetRequest\x1a\x19.Model.GetDataSetResponse\x12\x41\n\nCommitTree\x12\x18.Model.CommitTreeRequest\x1a\x19.Model.CommitTreeResponseb\x06proto3'
)




_GETDATASETREQUEST = _descriptor.Descriptor(
  name='GetDataSetRequest',
  full_name='Model.GetDataSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Model.GetDataSetRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=55,
)


_GETDATASETRESPONSE_ROWDATA = _descriptor.Descriptor(
  name='Rowdata',
  full_name='Model.GetDataSetResponse.Rowdata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='Model.GetDataSetResponse.Rowdata.row', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=186,
)

_GETDATASETRESPONSE = _descriptor.Descriptor(
  name='GetDataSetResponse',
  full_name='Model.GetDataSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Model.GetDataSetResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='labels', full_name='Model.GetDataSetResponse.labels', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='labelType', full_name='Model.GetDataSetResponse.labelType', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETDATASETRESPONSE_ROWDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=186,
)


_TREENODE = _descriptor.Descriptor(
  name='TreeNode',
  full_name='Model.TreeNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='Model.TreeNode.feature', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='Model.TreeNode.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='branches', full_name='Model.TreeNode.branches', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='Model.TreeNode.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=188,
  serialized_end=277,
)


_BRANCH_BRANCHESENTRY = _descriptor.Descriptor(
  name='BranchesEntry',
  full_name='Model.Branch.BranchesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Model.Branch.BranchesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Model.Branch.BranchesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=400,
)

_BRANCH = _descriptor.Descriptor(
  name='Branch',
  full_name='Model.Branch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='branches', full_name='Model.Branch.branches', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BRANCH_BRANCHESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=400,
)


_COMMITTREEREQUEST_TREEENTRY = _descriptor.Descriptor(
  name='TreeEntry',
  full_name='Model.CommitTreeRequest.TreeEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Model.CommitTreeRequest.TreeEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Model.CommitTreeRequest.TreeEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=534,
)

_COMMITTREEREQUEST = _descriptor.Descriptor(
  name='CommitTreeRequest',
  full_name='Model.CommitTreeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tree', full_name='Model.CommitTreeRequest.tree', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_COMMITTREEREQUEST_TREEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=534,
)


_COMMITTREERESPONSE = _descriptor.Descriptor(
  name='CommitTreeResponse',
  full_name='Model.CommitTreeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='Model.CommitTreeResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=568,
)

_GETDATASETRESPONSE_ROWDATA.containing_type = _GETDATASETRESPONSE
_GETDATASETRESPONSE.fields_by_name['data'].message_type = _GETDATASETRESPONSE_ROWDATA
_TREENODE.fields_by_name['branches'].message_type = _BRANCH
_TREENODE.oneofs_by_name['value'].fields.append(
  _TREENODE.fields_by_name['result'])
_TREENODE.fields_by_name['result'].containing_oneof = _TREENODE.oneofs_by_name['value']
_TREENODE.oneofs_by_name['value'].fields.append(
  _TREENODE.fields_by_name['branches'])
_TREENODE.fields_by_name['branches'].containing_oneof = _TREENODE.oneofs_by_name['value']
_BRANCH_BRANCHESENTRY.fields_by_name['value'].message_type = _TREENODE
_BRANCH_BRANCHESENTRY.containing_type = _BRANCH
_BRANCH.fields_by_name['branches'].message_type = _BRANCH_BRANCHESENTRY
_COMMITTREEREQUEST_TREEENTRY.fields_by_name['value'].message_type = _TREENODE
_COMMITTREEREQUEST_TREEENTRY.containing_type = _COMMITTREEREQUEST
_COMMITTREEREQUEST.fields_by_name['tree'].message_type = _COMMITTREEREQUEST_TREEENTRY
DESCRIPTOR.message_types_by_name['GetDataSetRequest'] = _GETDATASETREQUEST
DESCRIPTOR.message_types_by_name['GetDataSetResponse'] = _GETDATASETRESPONSE
DESCRIPTOR.message_types_by_name['TreeNode'] = _TREENODE
DESCRIPTOR.message_types_by_name['Branch'] = _BRANCH
DESCRIPTOR.message_types_by_name['CommitTreeRequest'] = _COMMITTREEREQUEST
DESCRIPTOR.message_types_by_name['CommitTreeResponse'] = _COMMITTREERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetDataSetRequest = _reflection.GeneratedProtocolMessageType('GetDataSetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDATASETREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Model.GetDataSetRequest)
  })
_sym_db.RegisterMessage(GetDataSetRequest)

GetDataSetResponse = _reflection.GeneratedProtocolMessageType('GetDataSetResponse', (_message.Message,), {

  'Rowdata' : _reflection.GeneratedProtocolMessageType('Rowdata', (_message.Message,), {
    'DESCRIPTOR' : _GETDATASETRESPONSE_ROWDATA,
    '__module__' : 'service_pb2'
    # @@protoc_insertion_point(class_scope:Model.GetDataSetResponse.Rowdata)
    })
  ,
  'DESCRIPTOR' : _GETDATASETRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Model.GetDataSetResponse)
  })
_sym_db.RegisterMessage(GetDataSetResponse)
_sym_db.RegisterMessage(GetDataSetResponse.Rowdata)

TreeNode = _reflection.GeneratedProtocolMessageType('TreeNode', (_message.Message,), {
  'DESCRIPTOR' : _TREENODE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Model.TreeNode)
  })
_sym_db.RegisterMessage(TreeNode)

Branch = _reflection.GeneratedProtocolMessageType('Branch', (_message.Message,), {

  'BranchesEntry' : _reflection.GeneratedProtocolMessageType('BranchesEntry', (_message.Message,), {
    'DESCRIPTOR' : _BRANCH_BRANCHESENTRY,
    '__module__' : 'service_pb2'
    # @@protoc_insertion_point(class_scope:Model.Branch.BranchesEntry)
    })
  ,
  'DESCRIPTOR' : _BRANCH,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Model.Branch)
  })
_sym_db.RegisterMessage(Branch)
_sym_db.RegisterMessage(Branch.BranchesEntry)

CommitTreeRequest = _reflection.GeneratedProtocolMessageType('CommitTreeRequest', (_message.Message,), {

  'TreeEntry' : _reflection.GeneratedProtocolMessageType('TreeEntry', (_message.Message,), {
    'DESCRIPTOR' : _COMMITTREEREQUEST_TREEENTRY,
    '__module__' : 'service_pb2'
    # @@protoc_insertion_point(class_scope:Model.CommitTreeRequest.TreeEntry)
    })
  ,
  'DESCRIPTOR' : _COMMITTREEREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Model.CommitTreeRequest)
  })
_sym_db.RegisterMessage(CommitTreeRequest)
_sym_db.RegisterMessage(CommitTreeRequest.TreeEntry)

CommitTreeResponse = _reflection.GeneratedProtocolMessageType('CommitTreeResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMITTREERESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Model.CommitTreeResponse)
  })
_sym_db.RegisterMessage(CommitTreeResponse)


_BRANCH_BRANCHESENTRY._options = None
_COMMITTREEREQUEST_TREEENTRY._options = None

_MANAGER = _descriptor.ServiceDescriptor(
  name='Manager',
  full_name='Model.Manager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=571,
  serialized_end=714,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDataSet',
    full_name='Model.Manager.GetDataSet',
    index=0,
    containing_service=None,
    input_type=_GETDATASETREQUEST,
    output_type=_GETDATASETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CommitTree',
    full_name='Model.Manager.CommitTree',
    index=1,
    containing_service=None,
    input_type=_COMMITTREEREQUEST,
    output_type=_COMMITTREERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MANAGER)

DESCRIPTOR.services_by_name['Manager'] = _MANAGER

# @@protoc_insertion_point(module_scope)
